"""
FORGE 2.3 Intelligent Collector — Orchestrator

Replaces the monolithic forge_collector.py with a modular pipeline:
  Probe → Validate → Classify → Score → Output

Supports two execution modes:
  - Config mode: Load pre-computed relevance map from Kiro Skill,
    skip probe/validate/detect phases, go straight to scoring.
  - Full pipeline: Execute probe → validate → classify → score for backward compatibility.
"""
import json
from datetime import datetime, timezone
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from forge.models import (
    RelevanceStatus,
    CriterionType,
    CriterionResult,
    PillarScore,
    ForgeAssessmentResult,
    RelevanceConfig,
    EstateAssessmentResult,
    PlatformSegment,
)
from forge.profile_engine import (
    ForgeProfile,
    ResolvedProfile,
    load_profile,
    resolve_profile,
)
from forge.relevance_engine.probes import run_probes
from forge.relevance_engine.validator import validate_service
from forge.relevance_engine.classifier import classify_criterion_relevance
from forge.scoring_engine.analog import score_criterion
from forge.scoring_engine.formula import (
    compute_raw_score,
    compute_coverage_multiplier,
    compute_forge_score,
)
from forge.scoring_engine.bands import classify_band
from forge.criteria_registry import (
    CRITERIA_REGISTRY,
    PILLAR_NAMES,
    get_criteria_for_pillar,
)


VERSION = "2.3.0"

# Role scope display — maps each pillar to its specific granted actions
_ROLE_SCOPE_ENTRIES = [
    ("P1 Agent Access & Discovery", "glue:GetDatabases, glue:GetTables, glue:GetCrawlers, lakeformation:ListResources, lambda:ListFunctions"),
    ("P2 Semantic Context & Retrieval", "s3:ListAllMyBuckets, bedrock:ListFoundationModels, bedrock-agent:ListKnowledgeBases"),
    ("P3 Data Lineage & Provenance", "neptune:DescribeDBClusters, es:ListDomainNames, es:DescribeDomains"),
    ("P4 Data Quality & Classification", "macie2:GetMacieSession, dynamodb:ListTables, rds:DescribeDBInstances, redshift:DescribeClusters"),
    ("P5 Access Control & Identity", "iam:ListRoles, iam:GetPolicy, cognito-idp:ListUserPools, access-analyzer:ListAnalyzers"),
    ("P6 Observability & Audit", "cloudtrail:DescribeTrails, cloudtrail:LookupEvents, config:DescribeConfigRules, cloudwatch:DescribeAlarms, xray:GetGroups"),
    ("P7 Real-Time Freshness", "kinesis:ListStreams, kafka:ListClustersV2, events:ListRules, sns:ListTopics"),
    ("P8 Agent Controllability", "lambda:ListFunctions, apigateway:GetRestApis, states:ListStateMachines, sagemaker:ListEndpoints"),
    ("P9 Decision Lineage", "athena:ListWorkGroups, athena:ListDataCatalogs, ce:GetCostAndUsage"),
]

_SECURITY_NOTE = "Least-privilege: only specific actions granted — no wildcards, no deny needed"


def display_role_scope() -> None:
    """Print a numbered summary of the FORGE-Assessment-Role permission scopes.

    Called once after the role is assumed, before probing starts. Informational only —
    does not block execution. All statements use specific actions (no wildcards).
    """
    separator = "────────────────────────────────────────────────"

    print(f"\n🔒 FORGE-Assessment-Role Permission Summary (Least-Privilege):")
    print(separator)

    for idx, (label, actions) in enumerate(_ROLE_SCOPE_ENTRIES, start=1):
        print(f" {idx}. {label}: {actions}")

    print(separator)
    print(f" ✓ {_SECURITY_NOTE}")
    print(f"{separator}\n")


def run_assessment(
    account_id: str,
    region: str,
    profile_path: Path = Path("forge_output/forge_profile.yaml"),
    customer_name: str = "Assessment Target",
    relevance_config: RelevanceConfig = None,
    profile_name: str = None,
) -> ForgeAssessmentResult:
    """Execute a FORGE 2.3 assessment.

    Two modes of operation:

    Config mode (relevance_config provided):
        Load the pre-computed relevance map generated by the Kiro Skill.
        Skip probe, validate, and detect phases. Go straight to scoring.

    Legacy mode (no relevance_config):
        Execute full pipeline: probe → validate → classify → score.

    Args:
        account_id: 12-digit AWS account ID being assessed.
        region: AWS region to assess.
        profile_path: Path to the forge_profile.yaml file (contains the locked
            FORGE Profile declaration).
        customer_name: Display name for the assessment target.
        relevance_config: Pre-computed relevance config from Kiro Skill.
            If provided, skips probe/validate/detect phases.
        profile_name: AWS CLI profile name for boto3 session (full pipeline).

    Returns:
        ForgeAssessmentResult with metadata, per-pillar scores, and summary.
    """
    start_time = datetime.now(timezone.utc)

    # Load and resolve the FORGE Profile
    profile = load_profile(profile_path)
    resolved = resolve_profile(profile)
    effective_weights = resolved.effective_weights
    effective_floors = resolved.effective_floors

    # Display role permission scope summary (informational only, does not block)
    display_role_scope()

    if relevance_config is not None:
        # Config mode: use pre-computed relevance map
        criterion_results = _run_config_mode(relevance_config)
    else:
        # Full pipeline: execute probe → validate → classify → score
        criterion_results = _run_full_pipeline(
            region, None, profile_name
        )

    # Build per-pillar scores from criterion results
    pillars = _build_pillar_scores(criterion_results)

    # Compute pillar percentage map for formula
    pillar_pct_map = {p.code: p.raw_score for p in pillars}

    # Apply FORGE score formula using profile-derived weights and floors
    raw_score = compute_raw_score(pillar_pct_map, effective_weights)
    coverage_multiplier = compute_coverage_multiplier(pillar_pct_map, effective_floors)

    forge_score = compute_forge_score(raw_score, coverage_multiplier)
    readiness_band = classify_band(forge_score)

    end_time = datetime.now(timezone.utc)
    duration = (end_time - start_time).total_seconds()

    # Criteria breakdown
    relevant_count = sum(
        1 for cr in criterion_results if cr.relevance_status == RelevanceStatus.RELEVANT
    )
    not_applicable_count = sum(
        1 for cr in criterion_results if cr.relevance_status == RelevanceStatus.NOT_APPLICABLE
    )
    undetermined_count = sum(
        1 for cr in criterion_results if cr.relevance_status == RelevanceStatus.UNDETERMINED
    )

    # Profile info for metadata and summary
    profile_dict = {
        "architecture": profile.architecture.value,
        "workload": profile.workload.value,
        "industry": profile.industry.value,
        "agent_maturity": profile.agent_maturity.value,
    }

    # Build metadata
    metadata = {
        "account_id": account_id,
        "region": region,
        "customer_name": customer_name,
        "timestamp": start_time.isoformat(),
        "collector_version": VERSION,
        "assessment_duration_seconds": round(duration, 2),
        "relevance_config_used": relevance_config is not None,
        "profile": profile_dict,
    }

    # Build summary
    summary = {
        "forge_score": forge_score,
        "readiness_band": readiness_band.value,
        "raw_score": round(raw_score, 2),
        "coverage_multiplier": round(coverage_multiplier, 4),
        "effective_weights": effective_weights,
        "effective_floors": effective_floors,
        "pillar_scores": {p.code: p.raw_score for p in pillars},
        "criteria_breakdown": {
            "relevant": relevant_count,
            "not_applicable": not_applicable_count,
            "undetermined": undetermined_count,
        },
        "profile": profile_dict,
    }

    # Append history record (graceful failure)
    _append_history_record(
        start_time=start_time,
        forge_score=forge_score,
        readiness_band=readiness_band,
        pillar_pct_map=pillar_pct_map,
        profile=profile,
    )

    # Write assessment JSON artifact (graceful failure)
    _write_assessment_json(
        start_time=start_time,
        metadata=metadata,
        profile_dict=profile_dict,
        effective_weights=effective_weights,
        effective_floors=effective_floors,
        coverage_multiplier=coverage_multiplier,
        pillars=pillars,
        forge_score=forge_score,
        readiness_band=readiness_band,
        raw_score=raw_score,
        criterion_results=criterion_results,
    )

    # Write roadmap markdown artifact (graceful failure)
    _write_roadmap_md(
        start_time=start_time,
        pillars=pillars,
        pillar_pct_map=pillar_pct_map,
        effective_weights=effective_weights,
        forge_score=forge_score,
        readiness_band=readiness_band,
    )

    return ForgeAssessmentResult(
        metadata=metadata,
        pillars=pillars,
        summary=summary,
    )


def _append_history_record(
    start_time: datetime,
    forge_score: float,
    readiness_band,
    pillar_pct_map: dict[str, float],
    profile: ForgeProfile,
) -> None:
    """Append a single JSONL record to forge_history.jsonl.

    Creates the file if it does not exist. Opens in append mode only.
    Reports but does not abort on filesystem write failures.
    """
    history_record = {
        "timestamp": start_time.isoformat(),
        "forge_score": forge_score,
        "score_band": readiness_band.value,
        "pillar_scores": pillar_pct_map,
        "profile": {
            "architecture": profile.architecture.value,
            "workload": profile.workload.value,
            "industry": profile.industry.value,
            "agent_maturity": profile.agent_maturity.value,
        },
    }
    try:
        import os
        os.makedirs("forge_output", exist_ok=True)
        with open("forge_output/forge_history.jsonl", "a") as f:
            f.write(json.dumps(history_record) + "\n")
    except OSError as e:
        print(f"Warning: Could not write to forge_output/forge_history.jsonl: {e}")


def _write_assessment_json(
    start_time: datetime,
    metadata: dict,
    profile_dict: dict,
    effective_weights: dict[str, float],
    effective_floors: dict[str, int],
    coverage_multiplier: float,
    pillars: list[PillarScore],
    forge_score: float,
    readiness_band,
    raw_score: float,
    criterion_results: list[CriterionResult],
) -> None:
    """Write forge_assessment_<ts>.json with full assessment details.

    Reports but does not abort on filesystem write failures.
    """
    import os
    ts_filename = start_time.strftime("%Y-%m-%dT%H-%M-%SZ")
    os.makedirs("forge_output/assessments", exist_ok=True)
    filename = f"forge_output/assessments/forge_assessment_{ts_filename}.json"

    # Build pillar detail for the output
    pillars_output = []
    for pillar in pillars:
        criteria_output = []
        for cr in pillar.criteria:
            criteria_output.append({
                "index": cr.index,
                "name": cr.name,
                "score": cr.score,
                "relevance_status": cr.relevance_status.value,
                "confidence_score": cr.confidence_score,
                "criterion_type": cr.criterion_type.value,
                "evidence": cr.evidence,
                "exclusion_reason": cr.exclusion_reason,
            })
        pillars_output.append({
            "code": pillar.code,
            "name": pillar.name,
            "raw_score": pillar.raw_score,
            "relevant_count": pillar.relevant_count,
            "not_applicable_count": pillar.not_applicable_count,
            "undetermined_count": pillar.undetermined_count,
            "criteria": criteria_output,
        })

    output = {
        "metadata": metadata,
        "profile": profile_dict,
        "effective_weights": effective_weights,
        "effective_floors": effective_floors,
        "pillars": pillars_output,
        "scoring": {
            "forge_score": forge_score,
            "score_band": readiness_band.value,
            "raw_score": round(raw_score, 2),
            "coverage_multiplier": round(coverage_multiplier, 4),
        },
    }

    try:
        with open(filename, "w") as f:
            json.dump(output, f, indent=2)
    except OSError as e:
        print(f"Warning: Could not write {filename}: {e}")


def _load_recommendations() -> dict | None:
    """Load forge_config/recommendations.yaml if available.

    Returns parsed dict keyed by criterion ID (e.g. 'P1.7') or None.
    """
    candidates = [
        Path("forge_config/recommendations.yaml"),
        Path(__file__).resolve().parent.parent / "forge_config" / "recommendations.yaml",
    ]

    config_path = None
    for candidate in candidates:
        if candidate.exists():
            config_path = candidate
            break

    if config_path is None:
        return None

    try:
        import yaml
    except ImportError:
        return None

    try:
        with open(config_path, "r") as f:
            return yaml.safe_load(f)
    except (OSError, Exception):
        return None


def _load_partner_solutions() -> dict | None:
    """Load forge_config/partner_solutions.yaml if available.

    Returns parsed dict with a 'solutions' list or None.
    """
    candidates = [
        Path("forge_config/partner_solutions.yaml"),
        Path(__file__).resolve().parent.parent / "forge_config" / "partner_solutions.yaml",
    ]

    config_path = None
    for candidate in candidates:
        if candidate.exists():
            config_path = candidate
            break

    if config_path is None:
        return None

    try:
        import yaml
    except ImportError:
        return None

    try:
        with open(config_path, "r") as f:
            return yaml.safe_load(f)
    except (OSError, Exception):
        return None


def _write_roadmap_md(
    start_time: datetime,
    pillars: list[PillarScore],
    pillar_pct_map: dict[str, float],
    effective_weights: dict[str, float],
    forge_score: float,
    readiness_band,
) -> None:
    """Write forge_roadmap_<ts>.md with remediation sorted by score-lift potential.

    Score-lift for a pillar is estimated as:
        potential_gain = (100 - pillar_score) * (effective_weight / 100)

    Pillars are sorted by potential_gain descending (highest lift first).
    If forge_config/recommendations.yaml exists, includes AWS and partner
    solution guidance for each unmet criterion.
    Reports but does not abort on filesystem write failures.
    """
    import os
    ts_filename = start_time.strftime("%Y-%m-%dT%H-%M-%SZ")
    os.makedirs("forge_output/roadmaps", exist_ok=True)
    filename = f"forge_output/roadmaps/forge_roadmap_{ts_filename}.md"

    # Load recommendations and partner solutions (graceful if unavailable)
    recommendations = _load_recommendations()
    partner_catalog = _load_partner_solutions()

    # Build partner ID → name lookup
    partner_names = {}
    if partner_catalog and "solutions" in partner_catalog:
        for sol in partner_catalog["solutions"]:
            partner_names[sol["id"]] = sol.get("name", sol["id"])

    # Compute score-lift potential per pillar
    pillar_lifts = []
    for pillar in pillars:
        weight = effective_weights.get(pillar.code, 0.0)
        potential_gain = (100.0 - pillar.raw_score) * (weight / 100.0)
        unmet_criteria = [
            cr for cr in pillar.criteria
            if cr.relevance_status == RelevanceStatus.RELEVANT and cr.score < 0.5
        ]
        pillar_lifts.append({
            "code": pillar.code,
            "name": pillar.name,
            "score": pillar.raw_score,
            "weight": weight,
            "potential_gain": round(potential_gain, 2),
            "unmet_criteria": unmet_criteria,
        })

    # Sort by score-lift potential descending
    pillar_lifts.sort(key=lambda x: x["potential_gain"], reverse=True)

    # Generate markdown
    lines = [
        f"# FORGE Remediation Roadmap",
        f"",
        f"**Generated:** {start_time.isoformat()}",
        f"**Current FORGE Score:** {forge_score} ({readiness_band.value})",
        f"",
        f"## Remediation Priorities (by Score-Lift Potential)",
        f"",
        f"Pillars are ranked by their potential contribution to improving the overall FORGE Score.",
        f"",
    ]

    for item in pillar_lifts:
        if item["potential_gain"] <= 0:
            continue

        lines.append(f"### {item['code']}: {item['name']}")
        lines.append(f"")
        lines.append(f"- **Current Score:** {item['score']}%")
        lines.append(f"- **Effective Weight:** {item['weight']:.1f}%")
        lines.append(f"- **Potential Score Lift:** +{item['potential_gain']:.2f} points")
        lines.append(f"")

        if item["unmet_criteria"]:
            lines.append(f"**Unmet Criteria ({len(item['unmet_criteria'])}):**")
            lines.append(f"")
            for cr in item["unmet_criteria"]:
                criterion_key = f"{item['code']}.{cr.index}"
                lines.append(f"- [ ] {criterion_key} — {cr.name}")
                if cr.evidence and cr.evidence != "No evidence":
                    lines.append(f"  - Evidence: {cr.evidence}")

                # Include recommendations if available
                if recommendations and criterion_key in recommendations:
                    rec = recommendations[criterion_key]
                    if rec.get("action"):
                        lines.append(f"  - **Action:** {rec['action']}")
                    if rec.get("effort") or rec.get("estimated_days"):
                        effort_str = rec.get("effort", "unknown")
                        days_str = f"{rec['estimated_days']}d" if rec.get("estimated_days") else "TBD"
                        lines.append(f"  - **Effort:** {effort_str} (~{days_str})")

                    # AWS solutions
                    aws_sols = rec.get("aws_solutions", [])
                    if aws_sols:
                        lines.append(f"  - **AWS Solutions:**")
                        for sol in aws_sols:
                            lines.append(f"    - {sol['service']}: {sol['action']}")

                    # Partner solutions
                    partner_sols = rec.get("partner_solutions", [])
                    if partner_sols:
                        lines.append(f"  - **Partner Solutions:**")
                        for pid in partner_sols:
                            pname = partner_names.get(pid, pid)
                            lines.append(f"    - {pname}")

                    # Also check partner catalog for solutions that list this criterion
                    if partner_catalog and "solutions" in partner_catalog and not partner_sols:
                        applicable_partners = [
                            s for s in partner_catalog["solutions"]
                            if criterion_key in s.get("applicable_criteria", [])
                        ]
                        if applicable_partners:
                            lines.append(f"  - **Applicable Partner Products:**")
                            for ap in applicable_partners:
                                lines.append(f"    - {ap['name']} ({ap.get('category', '')})")

            lines.append(f"")
        else:
            lines.append(f"_No unmet criteria identified in this pillar._")
            lines.append(f"")

    content = "\n".join(lines)

    try:
        with open(filename, "w") as f:
            f.write(content)
    except OSError as e:
        print(f"Warning: Could not write {filename}: {e}")


def _run_config_mode(
    relevance_config: RelevanceConfig,
) -> list[CriterionResult]:
    """Execute scoring using pre-computed relevance map (config mode).

    In config mode, the Kiro Skill has already performed probe/validate/detect,
    so we just map each criterion to its pre-determined relevance status and
    score accordingly.

    Returns:
        List of criterion results.
    """
    criterion_results = []

    for criterion in CRITERIA_REGISTRY:
        criterion_key = f"{criterion.pillar}.{criterion.index}"

        # Look up pre-computed relevance status
        relevance_value = relevance_config.criteria_relevance.get(criterion_key)
        if relevance_value is None:
            # Default to RELEVANT if not in config
            relevance_status = RelevanceStatus.RELEVANT
            exclusion_reason = None
        elif isinstance(relevance_value, RelevanceStatus):
            relevance_status = relevance_value
            exclusion_reason = None if relevance_status == RelevanceStatus.RELEVANT else (
                f"Pre-computed as {relevance_status.value} by relevance config"
            )
        else:
            # String value from JSON deserialization
            try:
                relevance_status = RelevanceStatus(relevance_value)
            except ValueError:
                relevance_status = RelevanceStatus.RELEVANT
            exclusion_reason = None if relevance_status == RelevanceStatus.RELEVANT else (
                f"Pre-computed as {relevance_status.value} by relevance config"
            )

        # Determine confidence from config services
        confidence = _get_confidence_from_config(criterion, relevance_config)

        # Score criterion: placeholder 0.0 for relevant criteria
        # (deep assessment logic is not wired in the new orchestrator)
        if relevance_status == RelevanceStatus.RELEVANT:
            score = 0.0
            evidence = "Placeholder — deep assessment not wired in config mode"
        elif relevance_status == RelevanceStatus.UNDETERMINED:
            score = 0.0
            evidence = "Undetermined relevance — scored as 0"
        else:
            score = 0.0
            evidence = exclusion_reason or "Not applicable"

        criterion_results.append(CriterionResult(
            pillar=criterion.pillar,
            index=criterion.index,
            name=criterion.name,
            score=score,
            relevance_status=relevance_status,
            confidence_score=confidence,
            evidence=evidence,
            criterion_type=criterion.criterion_type,
            exclusion_reason=exclusion_reason,
            confidence_reduced=(relevance_status == RelevanceStatus.UNDETERMINED),
        ))

    return criterion_results


def _run_full_pipeline(
    region: str,
    role_arn: str = None,
    profile_name: str = None,
) -> list[CriterionResult]:
    """Execute full pipeline: probe → validate → classify → score.

    Returns:
        List of criterion results.
    """
    # Phase 1: Probe all services (using direct session, no role assumption in full pipeline)
    probe_results = run_probes(region, profile_name=profile_name)
    probe_map = {p.service_name: p for p in probe_results}

    # Phase 2: Validate provisioned services
    from forge.models import ServiceClassification
    provisioned = [
        p for p in probe_results
        if p.classification == ServiceClassification.PROVISIONED
    ]
    validation_map = {}
    with ThreadPoolExecutor(max_workers=5) as executor:
        futures = {
            executor.submit(validate_service, p.service_name, region, None, profile_name): p
            for p in provisioned
        }
        for future in futures:
            result = future.result()
            validation_map[result.service_name] = result

    # Phase 3: Run deep assessment using pillar assessors
    from forge.pillar_assessors import run_pillar_assessors
    assessor_results = run_pillar_assessors(region, profile_name)

    # Phase 4: Classify relevance and score each criterion
    criterion_results = []
    for criterion in CRITERIA_REGISTRY:
        relevance_status, reason = classify_criterion_relevance(
            criterion, probe_map, validation_map
        )

        # Determine confidence score from validation data
        confidence = _get_confidence_from_validation(criterion, validation_map)

        # Get the real score from pillar assessors
        if relevance_status == RelevanceStatus.NOT_APPLICABLE:
            score = 0.0
            evidence = reason
        elif relevance_status == RelevanceStatus.UNDETERMINED:
            score = 0.0
            evidence = reason
        else:
            # Look up the criterion in assessor results
            pillar_result = assessor_results.get(criterion.pillar, {})
            pillar_criteria_list = pillar_result.get("criteria", [])
            criterion_match = None
            for lc in pillar_criteria_list:
                if lc.get("index") == criterion.index:
                    criterion_match = lc
                    break

            if criterion_match:
                score = 1.0 if criterion_match.get("met") else 0.0
                evidence = criterion_match.get("evidence", {}).get("description", "No evidence")
            else:
                score = 0.0
                evidence = "No assessor result for this criterion"

        criterion_results.append(CriterionResult(
            pillar=criterion.pillar,
            index=criterion.index,
            name=criterion.name,
            score=score,
            relevance_status=relevance_status,
            confidence_score=confidence,
            evidence=evidence,
            criterion_type=criterion.criterion_type,
            exclusion_reason=reason if relevance_status == RelevanceStatus.NOT_APPLICABLE else None,
            confidence_reduced=(relevance_status == RelevanceStatus.UNDETERMINED),
        ))

    return criterion_results


def _build_pillar_scores(criterion_results: list[CriterionResult]) -> list[PillarScore]:
    """Aggregate criterion results into per-pillar scores.

    Computes raw_score as:
        (sum of relevant criterion scores / relevant_count) * 100

    Criteria marked not-applicable are excluded from the calculation.
    """
    # Group criteria by pillar
    pillar_criteria: dict[str, list[CriterionResult]] = {}
    for cr in criterion_results:
        pillar_criteria.setdefault(cr.pillar, []).append(cr)

    pillars = []
    for code in sorted(PILLAR_NAMES.keys()):
        criteria = pillar_criteria.get(code, [])

        relevant = [
            cr for cr in criteria
            if cr.relevance_status in (RelevanceStatus.RELEVANT, RelevanceStatus.UNDETERMINED)
        ]
        not_applicable = [
            cr for cr in criteria
            if cr.relevance_status == RelevanceStatus.NOT_APPLICABLE
        ]
        undetermined = [
            cr for cr in criteria
            if cr.relevance_status == RelevanceStatus.UNDETERMINED
        ]

        relevant_count = len(relevant)
        not_applicable_count = len(not_applicable)
        undetermined_count = len(undetermined)

        # Compute raw score: average of relevant criterion scores * 100
        if relevant_count > 0:
            score_sum = sum(cr.score for cr in relevant)
            raw_score = round((score_sum / relevant_count) * 100, 2)
        else:
            raw_score = 0.0

        pillars.append(PillarScore(
            code=code,
            name=PILLAR_NAMES.get(code, code),
            raw_score=raw_score,
            relevant_count=relevant_count,
            not_applicable_count=not_applicable_count,
            undetermined_count=undetermined_count,
            criteria=criteria,
        ))

    return pillars


def _get_confidence_from_config(
    criterion, relevance_config: RelevanceConfig
) -> float:
    """Extract confidence score for a criterion from relevance config services."""
    if not criterion.services:
        return 1.0

    confidences = []
    for service in criterion.services:
        svc_data = relevance_config.services.get(service)
        if svc_data and isinstance(svc_data, dict):
            conf = svc_data.get("confidence", 0.5)
            confidences.append(conf)

    if confidences:
        return min(confidences)
    return 0.5  # Default when no service data available


def _get_confidence_from_validation(criterion, validation_map: dict) -> float:
    """Extract confidence score for a criterion from validation results."""
    if not criterion.services:
        return 1.0

    confidences = []
    for service in criterion.services:
        validation = validation_map.get(service)
        if validation:
            confidences.append(validation.confidence_score)

    if confidences:
        return min(confidences)
    return 0.5  # Default when no validation data available


def serialize_result(result: ForgeAssessmentResult) -> dict:
    """Convert a ForgeAssessmentResult dataclass into a JSON-serializable dict.

    Produces output matching the design's JSON schema with:
    - metadata: account_id, region, timestamp, collector_version, duration
    - pillars: per-pillar scores with per-criterion details
    - summary: forge_score, readiness_band, pillar_scores, coverage_multiplier, criteria_breakdown
    - scoring: dashboard format for forge_dashboard_generator.py compatibility

    The 'scoring' and 'pillars' top-level keys ensure the existing dashboard
    generator (which expects those keys) continues to work unchanged.

    Args:
        result: A ForgeAssessmentResult from run_assessment().

    Returns:
        A plain dict suitable for json.dump().
    """
    # Build per-pillar output
    pillars_output = []
    pillar_scores_dashboard = {}

    for pillar in result.pillars:
        criteria_output = []
        met_count = 0
        total_count = 0

        for cr in pillar.criteria:
            # Legacy dashboard compatibility: "met" = score >= 0.5 and relevant
            is_met = (
                cr.score >= 0.5
                and cr.relevance_status == RelevanceStatus.RELEVANT
            )
            if cr.relevance_status in (RelevanceStatus.RELEVANT, RelevanceStatus.UNDETERMINED):
                total_count += 1
                if is_met:
                    met_count += 1

            criteria_output.append({
                "index": cr.index,
                "name": cr.name,
                "score": cr.score,
                "met": is_met,
                "relevance_status": cr.relevance_status.value,
                "confidence_score": cr.confidence_score,
                "criterion_type": cr.criterion_type.value,
                "evidence": {
                    "description": cr.evidence,
                    "confidence_percent": round(cr.confidence_score * 100, 1),
                },
                "exclusion_reason": cr.exclusion_reason,
                "confidence_reduced": cr.confidence_reduced,
            })

        pillar_dict = {
            "code": pillar.code,
            "name": pillar.name,
            "total": total_count,
            "raw_score": pillar.raw_score,
            "relevant_count": pillar.relevant_count,
            "not_applicable_count": pillar.not_applicable_count,
            "undetermined_count": pillar.undetermined_count,
            "criteria": criteria_output,
        }
        pillars_output.append(pillar_dict)

        # Legacy format for dashboard generator
        pillar_scores_dashboard[pillar.code] = {
            "score_percent": pillar.raw_score,
            "met": met_count,
            "total": total_count,
        }

    # Build the full output dict
    output = {
        # Legacy top-level fields for forge_dashboard_generator.py compatibility
        "assessment_id": result.metadata.get("assessment_id", f"FORGE-{result.metadata.get('account_id', 'unknown')[:6]}"),
        "customer_name": result.metadata.get("customer_name", "Assessment Target"),
        "account_id": result.metadata.get("account_id", ""),
        "region": result.metadata.get("region", ""),
        "timestamp": result.metadata.get("timestamp", ""),
        "profile": result.metadata.get("profile", {}),
        # New modular format
        "metadata": result.metadata,
        "pillars": pillars_output,
        "summary": result.summary,
        # Legacy format for forge_dashboard_generator.py compatibility
        "scoring": {
            "forge_score": result.summary["forge_score"],
            "band": result.summary["readiness_band"],
            "raw_score": result.summary["raw_score"],
            "coverage_multiplier": result.summary["coverage_multiplier"],
            "pillar_scores": pillar_scores_dashboard,
            "penalty_percent": round((1.0 - result.summary["coverage_multiplier"]) * 100),
        },
    }

    return output


# ─── Estate-Level Assessment ───────────────────────────────────────────────────


def run_estate_assessment(
    segments: list[PlatformSegment],
    profile_path: Path = Path("forge_output/forge_profile.yaml"),
    customer_name: str = "Assessment Target",
) -> EstateAssessmentResult:
    """Run the estate-level assessment by merging platform segments.

    Takes pre-built platform segments (from AWS collector + Databricks skill),
    merges their criteria, and produces the estate score.

    Args:
        segments: List of PlatformSegment objects (at least one required).
        profile_path: Path to the forge_profile.yaml for weight/floor resolution.
        customer_name: Customer name for metadata.

    Returns:
        EstateAssessmentResult with all segments, merged criteria, and estate score.

    Raises:
        ValueError: If segments list is empty.
    """
    if not segments:
        raise ValueError("At least one platform segment is required")

    from forge.scoring_engine.merge import (
        merge_criteria,
        compute_estate_score,
        _build_pillar_scores_from_merged,
    )

    # Load profile
    profile = load_profile(profile_path)
    resolved = resolve_profile(profile)
    effective_weights = resolved.effective_weights
    effective_floors = resolved.effective_floors

    # Merge criteria across segments
    merged_criteria = merge_criteria(segments)

    # Compute estate score
    estate_score, estate_band, raw_score, coverage_multiplier = compute_estate_score(
        merged_criteria, effective_weights, effective_floors
    )

    # Build merged pillar scores (from merge engine)
    merged_pillars = _build_pillar_scores_from_merged(merged_criteria)

    # Build metadata
    metadata = {
        "customer_name": customer_name,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "collector_version": VERSION,
        "platforms_assessed": [s.platform for s in segments],
    }

    result = EstateAssessmentResult(
        segments=segments,
        merged_pillars=merged_pillars,
        merged_criteria=merged_criteria,
        estate_score=estate_score,
        estate_band=estate_band,
        estate_raw_score=raw_score,
        estate_coverage_multiplier=coverage_multiplier,
        metadata=metadata,
    )

    # Write estate JSON
    _write_estate_json(result, effective_weights, effective_floors)

    # Append estate history record (graceful failure)
    _append_estate_history_record(result, profile)

    # Write estate roadmap markdown (multi-platform, platform-grouped)
    _write_estate_roadmap_md(result, effective_weights)

    return result


def _write_estate_json(
    result: EstateAssessmentResult,
    effective_weights: dict[str, float],
    effective_floors: dict[str, int],
) -> None:
    """Write estate assessment JSON artifact to forge_output/assessments/.

    Produces a file named forge_estate_assessment_<ts>.json with the format:
    {
      "metadata": {...},
      "profile": {...},
      "effective_weights": {...},
      "effective_floors": {...},
      "estate": {forge_score, score_band, raw_score, coverage_multiplier},
      "segments": [...],
      "merged_pillars": [...],
      "merged_criteria": [...]
    }

    Reports but does not abort on filesystem write failures.
    """
    import os

    ts_filename = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H-%M-%SZ")
    os.makedirs("forge_output/assessments", exist_ok=True)
    filename = f"forge_output/assessments/forge_estate_assessment_{ts_filename}.json"

    # Build segments output
    segments_output = []
    for segment in result.segments:
        criteria_output = []
        for cr in segment.criteria:
            cr_dict = {
                "pillar": cr.pillar,
                "index": cr.index,
                "name": cr.name,
                "score": cr.score,
                "relevance_status": cr.relevance_status.value,
                "confidence_score": cr.confidence_score,
                "evidence": cr.evidence,
                "criterion_type": cr.criterion_type.value,
                "platform": cr.platform,
                "exclusion_reason": cr.exclusion_reason,
            }
            if cr.analog_detail is not None:
                cr_dict["analog_detail"] = {
                    "numerator": cr.analog_detail.numerator,
                    "denominator": cr.analog_detail.denominator,
                    "platform": cr.analog_detail.platform,
                }
            criteria_output.append(cr_dict)

        pillars_output = []
        for pillar in segment.pillars:
            pillars_output.append({
                "code": pillar.code,
                "name": pillar.name,
                "raw_score": pillar.raw_score,
                "relevant_count": pillar.relevant_count,
                "not_applicable_count": pillar.not_applicable_count,
                "undetermined_count": pillar.undetermined_count,
            })

        segments_output.append({
            "platform": segment.platform,
            "source_type": segment.source_type,
            "forge_score": segment.summary.get("forge_score"),
            "score_band": segment.summary.get("readiness_band"),
            "pillars": pillars_output,
            "criteria": criteria_output,
        })

    # Build merged pillars output
    merged_pillars_output = []
    for pillar in result.merged_pillars:
        merged_pillars_output.append({
            "code": pillar.code,
            "name": pillar.name,
            "raw_score": pillar.raw_score,
            "relevant_count": pillar.relevant_count,
            "not_applicable_count": pillar.not_applicable_count,
            "undetermined_count": pillar.undetermined_count,
        })

    # Build merged criteria output
    merged_criteria_output = []
    for cr in result.merged_criteria:
        cr_dict = {
            "pillar": cr.pillar,
            "index": cr.index,
            "name": cr.name,
            "score": cr.score,
            "relevance_status": cr.relevance_status.value,
            "confidence_score": cr.confidence_score,
            "evidence": cr.evidence,
            "criterion_type": cr.criterion_type.value,
            "platform": cr.platform,
            "exclusion_reason": cr.exclusion_reason,
        }
        if cr.analog_detail is not None:
            cr_dict["analog_detail"] = {
                "numerator": cr.analog_detail.numerator,
                "denominator": cr.analog_detail.denominator,
                "platform": cr.analog_detail.platform,
            }
        merged_criteria_output.append(cr_dict)

    # Build full output
    output = {
        "metadata": result.metadata,
        "effective_weights": effective_weights,
        "effective_floors": effective_floors,
        "estate": {
            "forge_score": result.estate_score,
            "score_band": result.estate_band.value,
            "raw_score": round(result.estate_raw_score, 2),
            "coverage_multiplier": round(result.estate_coverage_multiplier, 4),
        },
        "segments": segments_output,
        "merged_pillars": merged_pillars_output,
        "merged_criteria": merged_criteria_output,
    }

    try:
        with open(filename, "w") as f:
            json.dump(output, f, indent=2)
    except OSError as e:
        print(f"Warning: Could not write {filename}: {e}")


def _append_estate_history_record(
    result: EstateAssessmentResult,
    profile: ForgeProfile,
) -> None:
    """Append an estate assessment record to forge_history.jsonl.

    Multi-platform format (len(segments) > 1):
    {
        "timestamp": "...",
        "estate_score": 59.8,
        "estate_band": "GOVERNED",
        "forge_score": 59.8,           # backward compat alias
        "score_band": "GOVERNED",      # backward compat alias
        "platform_scores": {"aws": 68.5, "databricks": 47.2},
        "pillar_scores": {"P1": 65.0, "P2": 55.0, ...},
        "platforms_assessed": ["aws", "databricks"],
        "profile": {...}
    }

    Backward compat (len(segments) == 1):
    Uses "forge_score" and "score_band" keys only (no estate_score/estate_band,
    no platform_scores, no platforms_assessed). Same format as existing
    _append_history_record output.

    Reports but does not abort on filesystem write failures.
    """
    # Build pillar scores from merged pillars
    pillar_scores = {p.code: p.raw_score for p in result.merged_pillars}

    # Profile dict
    profile_dict = {
        "architecture": profile.architecture.value,
        "workload": profile.workload.value,
        "industry": profile.industry.value,
        "agent_maturity": profile.agent_maturity.value,
    }

    timestamp = result.metadata.get("timestamp", datetime.now(timezone.utc).isoformat())

    if len(result.segments) == 1:
        # Single platform: backward-compatible format
        # Omit platform_scores and platforms_assessed
        history_record = {
            "timestamp": timestamp,
            "forge_score": result.estate_score,
            "score_band": result.estate_band.value,
            "pillar_scores": pillar_scores,
            "profile": profile_dict,
        }
    else:
        # Multi-platform: extended format
        platform_scores = {
            segment.platform: segment.summary.get("forge_score", 0.0)
            for segment in result.segments
        }
        history_record = {
            "timestamp": timestamp,
            "estate_score": result.estate_score,
            "estate_band": result.estate_band.value,
            "forge_score": result.estate_score,       # backward compat alias
            "score_band": result.estate_band.value,   # backward compat alias
            "platform_scores": platform_scores,
            "pillar_scores": pillar_scores,
            "platforms_assessed": [s.platform for s in result.segments],
            "profile": profile_dict,
        }

    try:
        import os
        os.makedirs("forge_output", exist_ok=True)
        with open("forge_output/forge_history.jsonl", "a") as f:
            f.write(json.dumps(history_record) + "\n")
    except OSError as e:
        print(f"Warning: Could not write to forge_output/forge_history.jsonl: {e}")


def _write_estate_roadmap_md(
    result: EstateAssessmentResult,
    effective_weights: dict[str, float],
) -> None:
    """Write multi-platform roadmap markdown to forge_output/roadmaps/.

    Produces a file named forge_estate_roadmap_<ts>.md with platform-grouped
    remediation sections. Each criterion is tagged with its platform.

    Format:
        # FORGE Estate Remediation Roadmap

        **Estate Score:** 59.8 (GOVERNED)
        **Platforms:** AWS (68.5), Databricks (47.2)

        ## AWS Remediation

        ### P1: Agent Access & Discovery
        - [ ] P1.6 — Catalog covers >80% (Evidence: ...)
        - [ ] P1.7 — Catalog descriptions (Evidence: ...)

        ## Databricks Remediation

        ### P4: Data Quality
        - [ ] P4.2 — Tables with DQ rules (Evidence: ...)
            - Services: Delta Live Tables

    Reports but does not abort on filesystem write failures.
    """
    import os

    ts_filename = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H-%M-%SZ")
    os.makedirs("forge_output/roadmaps", exist_ok=True)
    filename = f"forge_output/roadmaps/forge_estate_roadmap_{ts_filename}.md"

    # Import Databricks registry for service references
    try:
        from forge.platform_segments.databricks_registry import (
            DATABRICKS_SERVICES,
            get_databricks_criterion,
        )
        has_dbx_registry = True
    except ImportError:
        has_dbx_registry = False
        DATABRICKS_SERVICES = {}

    # Build header
    platform_scores_str = ", ".join(
        f"{seg.platform.upper()} ({seg.summary.get('forge_score', 0.0):.1f})"
        for seg in result.segments
    )

    lines = [
        "# FORGE Estate Remediation Roadmap",
        "",
        f"**Generated:** {result.metadata.get('timestamp', datetime.now(timezone.utc).isoformat())}",
        f"**Estate Score:** {result.estate_score:.1f} ({result.estate_band.value})",
        f"**Platforms:** {platform_scores_str}",
        "",
    ]

    # Group remediation by platform
    for segment in result.segments:
        # Find criteria with score < 0.5 and status RELEVANT for this platform
        unmet_criteria = [
            cr for cr in segment.criteria
            if cr.relevance_status == RelevanceStatus.RELEVANT and cr.score < 0.5
        ]

        if not unmet_criteria:
            lines.append(f"## {segment.platform.upper()} Remediation")
            lines.append("")
            lines.append("_No unmet criteria — all relevant criteria passing._")
            lines.append("")
            continue

        # Sort by pillar code, then by criterion index
        unmet_criteria.sort(key=lambda cr: (cr.pillar, cr.index))

        lines.append(f"## {segment.platform.upper()} Remediation")
        lines.append("")

        # Group by pillar
        current_pillar = None
        for cr in unmet_criteria:
            if cr.pillar != current_pillar:
                current_pillar = cr.pillar
                # Get pillar name from the segment's pillar scores
                pillar_name = current_pillar
                for p in segment.pillars:
                    if p.code == current_pillar:
                        pillar_name = p.name
                        break
                lines.append(f"### {current_pillar}: {pillar_name}")
                lines.append("")

            criterion_key = f"{cr.pillar}.{cr.index}"
            lines.append(f"- [ ] {criterion_key} — {cr.name}")

            # Add evidence if available
            if cr.evidence and cr.evidence != "No evidence":
                lines.append(f"  - Evidence: {cr.evidence}")

            # For Databricks criteria: include the service reference from registry
            if segment.platform == "databricks" and has_dbx_registry:
                dbx_criterion = get_databricks_criterion(cr.pillar, cr.index)
                if dbx_criterion and dbx_criterion.services:
                    service_names = [
                        DATABRICKS_SERVICES.get(svc, svc)
                        for svc in dbx_criterion.services
                    ]
                    lines.append(f"  - Services: {', '.join(service_names)}")

        lines.append("")

    content = "\n".join(lines)

    try:
        with open(filename, "w") as f:
            f.write(content)
    except OSError as e:
        print(f"Warning: Could not write {filename}: {e}")
